services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DATABASE_URL=sqlite:////app/var/data.db
    volumes:
    - ./chat-backend:/app
    # - ./chat-backend/vendor:/app/vendor

  frontend:
    build:
      context: .
      dockerfile: docker/svelte/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./chat-frontend:/app
      # Evita que se sobreescriba node_modules
      - /app/node_modules


