version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./chat-backend:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:////app/var/data.db
  frontend:
    build:
      context: .
      dockerfile: docker/svelte/Dockerfile
    volumes:
      - ./chat-frontend:/app
    ports:
      - "5173:5173"

