services:
    _defaults:
        autowire: true      # Inyecta dependencias automáticamente
        autoconfigure: true # Detecta controladores y comandos
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
